= Exercise 02
:author: Florian Weingartshofer
:email: <S1910307103@students.fh-hagenberg.at>
:reproducible:
:experimental:
:listing-caption: Listing
:source-highlighter: rouge
:rouge-style: github
:toc:
:sectnums:
:sectnumlevels: 6
:toclevels: 6
// Variables
:img: ./img
:imagesoutdir: ./out

<<<
== Race Conditions
=== Simple Race Condition
Two threads, both with "heavy" computation, try to increment the variable `i`.
Here is the possibility that in the first thread i is incremented first, but not yet written back.
Then the second thread increases i and writes the result back to i.
After that the first thread writes its result to i.
Thus i is effectively increased only once.

[cols="2,2,1,2"]
|===
|Thread 1 |Thread 2 | | Value of `i`

|
|
|
|0

|Read `i`
|
|
|0

|
|Read `i`
|
|0

|Increment `i`
|
|
|0

|
|Increment `i`
|
|0

|Write `i`
|
|
|1

|
|Write `i`
|
|1
|===

.Race Condition
[source,csharp]
----
include::../RaceConditions/Program.cs[lines=21..46]
----

The solution is to lock the part where `i` is incremented.
This can be done with `lock` and a locking object 
or alternatively the `Interlocked.Increment` method can be used, which would be a little bit shorter.

.No Race Condition
[source,csharp]
----
include::../RaceConditions/Program.cs[lines=9..9]
include::../RaceConditions/Program.cs[lines=48..82]
----

<<<
=== Race Condition Example
Instead of using an `AutoResetEvent` two semaphores are used, to fully use the buffer.
An semaphore is created, which counts the times the buffer was emptied, and another which counts the newly added elements.
Through that mechanism the buffer can be fully filled, but it does not override elements, which have not been read.
Instead of using two semaphores it is possible to use two `AutoResetEvents`, but this will not utilize the whole buffer.

[source,csharp]
----
include::../RaceConditions/RaceConditionExample.cs[]
----

<<<
== Synchronization Primitives
To limit the number of threads, a semaphore is used, with a maximum number of threads.

For the `DownloadFiles` method all threads are saved into a List and then joined to the main thread.

[source,csharp]
----
include::../LimitedConnectionsExample/LimitedConnectionsExample.cs[]
----

<<<
== Toilet Simulation
=== Fifo Queue
`a` and `b` have been implemented during the lecture.
Here are the test results:

.Fifo Queue Test Results
|===
| |Jobs |Starved Jobs |Starvation Ratio |Total Waiting Time |Mean Waiting Time

|1
|400
|261
|65.25%
|00:04:15.282
|00:00:00.638

|2
|400
|309
|77.25%
|00:06:10.973
|00:00:00.927

|3
|400
|57
|14.24%
|00:01:16.022
|00:00:00.190

|4
|400
|319
|79.75%
|00:05:50.957
|00:00:00.877

|5
|400
|349
|87.25%
|00:08:07.456
|00:00:01.219

|*Mean*
|400
|259
|64.75%
|00:05:08.138
|00:00:00.770

|*Standard Deviation*
|0
|117.2689217
|0.2932153679
|0.001780004569
|0.000004450011248
|===

=== Priority Ignore Irrelevant Jobs Queue aka Toilet Queue
Instead of a fifo queue, the toilet queue is implemented as a priority queue.
This places jobs that are due earlier than others at the top of the queue.
In addition to using a priority queue, the toilet queue ignores jobs whose due date is in the past,
if there are still orders whose due date is in the future.

.Toilet Queue
[source,csharp]
----
include::../ToiletSimulation/ToiletQueue.cs[]
----

The test results show that the priority queue is way better at not letting threads starve.

.Toilet Queue Test Results
|===
| |Jobs |Starved Jobs |Starvation Ratio |Total Waiting Time |Mean Waiting Time

|1
|400
|32
|8.00%
|00:01:12.394
|00:00:00.181

|2
|400
|133
|33.25%
|00:02:09.311
|00:00:00.323

|3
|400
|41
|10.25%
|00:00:58.051
|00:00:00.145

|4
|400
|47
|11.75%
|00:01:25.528
|00:00:00.214

|5
|400
|58
|14.50%
|00:01:22.769
|00:00:00.207

|*Mean*
|400
|62.2
|15.55%
|00:01:25.611
|00:00:00.214

|*Standard Deviation*
|0
|40.69029368
|0.1017257342
|0.0003090556546
|0.0000007726392076
|===